# Generated by Django 4.0.6 on 2022-07-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='FoodItem',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderFoodItems',
            new_name='OrderFoodItem',
        ),
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
